const q=s=>document.querySelector(s);
function setText(sel,text){const el=q(sel);if(el&&el.textContent!==text)el.textContent=text}
function syncLabels(version=6){setText('#engineVersionPill',`ENGINE v${version}`);setText('#integrityEngine',`v${version}`);const meta=q('#phaseTransitionMeta');if(meta?.textContent?.includes('Engine v5'))meta.textContent=meta.textContent.replaceAll('Engine v5',`Engine v${version}`)}
function appendPerfFlags(s){const flags=q('#integrityFlags');if(!flags||!s)return;flags.querySelectorAll('[data-v6-flag]').forEach(x=>x.remove());const d=s.phases?.download||{},u=s.phases?.upload||{},perf=s.performance||{};const items=[[`Profile ${perf.profile||s.performanceProfile||'—'}`,'neutral'],[d.saturationPlateau?'Download saturation tercapai':`Download max ${d.maxStreams||'—'} stream`,d.saturationPlateau?'good':'neutral'],[u.saturationPlateau?'Upload saturation tercapai':`Upload max ${u.maxStreams||'—'} stream`,u.saturationPlateau?'good':'neutral'],[`${perf.frameStalls||0} UI frame stall`,(perf.frameStalls||0)>5?'warn':'good']];for(const [text,tone] of items){const el=document.createElement('span');el.dataset.v6Flag='1';el.className=`integrity-flag ${tone}`;el.textContent=text;flags.append(el)}}
function installPerfCard(s){const panel=q('[data-workspace-panel="health"]');if(!panel||q('#enginePerfCard'))return;const card=document.createElement('article');card.id='enginePerfCard';card.className='panel dock-card advanced-card';card.innerHTML=`<div class="advanced-head"><div><span>ENGINE v6 PERFORMANCE</span><strong>Saturation & UI health</strong></div><span id="enginePerfBadge" class="advanced-badge">Adaptive</span></div><div class="integrity-grid"><div><span>Profile</span><b id="enginePerfProfile">—</b><small>device-aware</small></div><div><span>Download plateau</span><b id="engineDownPlateau">—</b><small>saturation</small></div><div><span>Upload plateau</span><b id="engineUpPlateau">—</b><small>saturation</small></div><div><span>UI frame stalls</span><b id="engineFrameStalls">—</b><small>&gt;110 ms gap</small></div></div>`;const audit=q('#resultAuditCard');if(audit)audit.after(card);else panel.append(card);paintPerf(s)}
function paintPerf(s){if(!s)return;const d=s.phases?.download||{},u=s.phases?.upload||{},p=s.performance||{};setText('#enginePerfProfile',p.profile||s.performanceProfile||'—');setText('#engineDownPlateau',d.saturationPlateau?'Tercapai':Number.isFinite(d.saturationGain)?`${Math.round(d.saturationGain*100)}% gain`:'—');setText('#engineUpPlateau',u.saturationPlateau?'Tercapai':Number.isFinite(u.saturationGain)?`${Math.round(u.saturationGain*100)}% gain`:'—');setText('#engineFrameStalls',String(p.frameStalls??'—'));const badge=q('#enginePerfBadge');if(badge){const stalls=Number(p.frameStalls)||0;badge.className=`advanced-badge ${stalls>8?'warn':'good'}`;badge.textContent=stalls>8?'UI terbebani':'UI sehat'}}
window.addEventListener('wifi-engine-ready',e=>syncLabels(e.detail?.version||6));
window.addEventListener('wifi-test-phase',()=>queueMicrotask(()=>syncLabels(window.wifiMeasurementSession?.version||6)),{passive:true});
window.addEventListener('wifi-measurement-session',e=>{const s=e.detail||window.wifiMeasurementSession;syncLabels(s?.version||6);appendPerfFlags(s);installPerfCard(s);paintPerf(s)});
let n=0;const ready=setInterval(()=>{n++;syncLabels(window.wifiMeasurementSession?.version||6);if(q('[data-workspace-panel="health"]')){clearInterval(ready);const s=window.wifiMeasurementSession;if(s?.status==='complete'){appendPerfFlags(s);installPerfCard(s)}}else if(n>120)clearInterval(ready)},100);
window.wifiEngineV6UI={version:1};
