const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const nextFrame=()=>new Promise(r=>requestAnimationFrame(()=>setTimeout(r,0)));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const connection=navigator.connection||navigator.mozConnection||navigator.webkitConnection;
const SPEED_BASE='https://speed.cloudflare.com';
const touchLike=matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0;
const cores=Math.max(1,Number(navigator.hardwareConcurrency)||4);
const memory=Number(navigator.deviceMemory)||0;
const performanceProfile=touchLike?'mobile':(cores>=8&&(memory===0||memory>=8)?'desktop':'balanced');

async function waitForCore(){for(let i=0;i<240;i++){if(typeof window.downloadRequest==='function'&&typeof window.uploadRequest==='function'&&typeof window.latencyProbe==='function')return true;await sleep(25)}return false}
function median(values){const a=values.filter(Number.isFinite).slice().sort((x,y)=>x-y);if(!a.length)return NaN;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function mean(values){const a=values.filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN}
function percentile(values,p){const a=values.filter(Number.isFinite).slice().sort((x,y)=>x-y);if(!a.length)return NaN;const idx=(a.length-1)*p,lo=Math.floor(idx),hi=Math.ceil(idx);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(idx-lo)}
function stdev(values){const a=values.filter(Number.isFinite);if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,v)=>s+(v-m)**2,0)/(a.length-1))}
function mad(values){const m=median(values);return median(values.map(v=>Math.abs(v-m)))}
function qualityLabel(score){return score>=90?'Sangat tinggi':score>=78?'Tinggi':score>=62?'Baik':score>=48?'Sedang':'Rendah'}
function humanMB(bytes){return `${(bytes/1e6).toFixed(bytes>=100e6?0:1)} MB`}
function clone(v){try{return structuredClone(v)}catch{return JSON.parse(JSON.stringify(v))}}
function snapshotConnection(){return{online:navigator.onLine,type:connection?.type||null,effectiveType:connection?.effectiveType||null,downlink:Number.isFinite(connection?.downlink)?connection.downlink:null,rtt:Number.isFinite(connection?.rtt)?connection.rtt:null,saveData:typeof connection?.saveData==='boolean'?connection.saveData:null}}
function sameConnection(a,b){return a?.online===b?.online&&a?.type===b?.type&&a?.effectiveType===b?.effectiveType&&a?.saveData===b?.saveData}
function phase(stage,message,detail={}){const a=document.getElementById('testStage'),b=document.getElementById('testMessage');if(a&&a.textContent!==stage)a.textContent=stage;if(b&&b.textContent!==message)b.textContent=message;window.dispatchEvent(new CustomEvent('wifi-test-phase',{detail:{stage,message,...detail}}))}

async function readEdge(){const c=new AbortController(),t=setTimeout(()=>c.abort(),2200);try{const r=await fetch(`${SPEED_BASE}/meta?r=${Date.now()}-${Math.random()}`,{cache:'no-store',signal:c.signal});if(!r.ok)return null;const m=await r.json();return{colo:m.colo||null,asn:m.asn||null,organization:m.asOrganization||m.asnOrganization||null,city:m.city||null,country:m.country||null}}catch{return null}finally{clearTimeout(t)}}
function rejectOutliers(values){const a=values.filter(Number.isFinite);if(a.length<4)return{values:a,dropped:0,indexes:[]};const m=median(a),d=mad(a),limit=Math.max(d*3.15,Math.abs(m)*.145,.2),indexes=[];a.forEach((v,i)=>{if(Math.abs(v-m)>limit)indexes.push(i)});const kept=a.filter((_,i)=>!indexes.includes(i));return kept.length>=Math.ceil(a.length*.6)?{values:kept,dropped:indexes.length,indexes}:{values:a,dropped:0,indexes:[]}}
function convergence(values){const a=rejectOutliers(values).values;if(a.length<3)return{score:0,spread:NaN,converged:false};const recent=a.slice(-Math.min(5,a.length)),m=median(recent),spread=Number.isFinite(m)&&m>0?(percentile(recent,.9)-percentile(recent,.1))/m:1;const score=Math.round(clamp(100-spread*205,0,100));return{score,spread,converged:score>=84}}
function ci90(values){const a=rejectOutliers(values).values;if(!a.length)return{low:NaN,high:NaN,margin:NaN,relativeWidth:NaN};const m=mean(a),sd=stdev(a),margin=a.length>1?1.645*sd/Math.sqrt(a.length):0,low=Math.max(0,m-margin),high=m+margin;return{low,high,margin,relativeWidth:m>0?(high-low)/m:NaN}}
function trendSlope(values){const a=values.filter(Number.isFinite);if(a.length<3)return 0;const n=a.length,xm=(n-1)/2,ym=mean(a);let num=0,den=0;for(let i=0;i<n;i++){num+=(i-xm)*(a[i]-ym);den+=(i-xm)**2}return den?num/den:0}
function contentionSignals(values){const a=rejectOutliers(values).values;if(a.length<4)return{suspected:false,oscillation:0,downwardDrift:false,cv:0};const m=mean(a),cv=m>0?stdev(a)/m:1;let turns=0;for(let i=2;i<a.length;i++){const d1=a[i-1]-a[i-2],d2=a[i]-a[i-1];if(d1*d2<0)turns++}const oscillation=turns/Math.max(1,a.length-2),slope=trendSlope(a),downwardDrift=m>0&&slope/m<-.032;return{suspected:cv>.19||oscillation>.68||downwardDrift,oscillation,downwardDrift,cv}}
function plateauState(points){const groups=new Map();for(const p of points){if(!Number.isFinite(p?.mbps)||!p?.streams)continue;const a=groups.get(p.streams)||[];a.push(p.mbps);groups.set(p.streams,a)}const keys=[...groups.keys()].sort((a,b)=>a-b);if(keys.length<2)return{plateau:false,gain:NaN,from:null,to:null};const to=keys.at(-1),from=keys.at(-2),a=median(groups.get(from)),b=median(groups.get(to)),gain=a>0?(b-a)/a:NaN;return{plateau:Number.isFinite(gain)&&gain<.055,gain,from,to}}
function summarize(values,target,elapsedMs,retries,failures,extra={}){const robust=rejectOutliers(values),a=robust.values,m=mean(a),sd=stdev(a),cv=m>0?sd/m:1,conv=convergence(a),range=ci90(a),contention=contentionSignals(a);const stability=Math.round(clamp(100-cv*125,0,100)),sampleScore=clamp(a.length/Math.max(1,target),0,1),durationScore=clamp(elapsedMs/5000,0,1),retryPenalty=clamp((retries+failures)/Math.max(1,values.length+failures),0,1),widthPenalty=Number.isFinite(range.relativeWidth)?clamp(range.relativeWidth/.35,0,1):1;const confidence=Math.round(clamp(stability*.34+conv.score*.24+sampleScore*100*.18+durationScore*100*.12+(100-retryPenalty*100)*.08+(100-widthPenalty*100)*.04-robust.dropped*2,0,100));const p50=median(a),p65=percentile(a,.65),sustained=Number.isFinite(p50)&&Number.isFinite(p65)?p50*.84+p65*.16:p50;return{count:a.length,rawCount:values.length,median:p50,sustained,mean:m,min:a.length?Math.min(...a):NaN,max:a.length?Math.max(...a):NaN,p10:percentile(a,.1),p65,p90:percentile(a,.9),stdev:sd,cv,stability,confidence,confidenceLabel:qualityLabel(confidence),retries,failures,successRate:Math.round(values.length/Math.max(1,values.length+failures)*100),elapsedMs,outliersDropped:robust.dropped,convergence:conv.score,converged:conv.converged,ci90Low:range.low,ci90High:range.high,ci90Margin:range.margin,relativeCIWidth:range.relativeWidth,contentionSuspected:contention.suspected,oscillation:contention.oscillation,downwardDrift:contention.downwardDrift,...extra}}

function streamLimits(direction,quick){if(quick)return 2;if(performanceProfile==='mobile')return direction==='download'?4:3;if(performanceProfile==='balanced')return direction==='download'?5:4;return direction==='download'?6:4}
function baseStreams(direction,estimate,quick){if(quick)return estimate>=100?2:1;let s=direction==='download'?(estimate>=300?5:estimate>=120?4:estimate>=35?3:2):(estimate>=180?4:estimate>=60?3:estimate>=15?2:1);return Math.min(s,streamLimits(direction,quick))}
function adaptiveStreams(direction,estimate,quick,index,points){let streams=baseStreams(direction,estimate,quick),max=streamLimits(direction,quick),values=points.map(x=>x.mbps),plateau=plateauState(points);if(!quick&&index>=2&&!plateau.plateau){const c=convergence(values);if(c.score<62)streams++;if(values.length>=2&&values.at(-1)>values.at(-2)*1.12)streams++}if(plateau.plateau)streams=Math.min(streams,plateau.to||streams);return Math.round(clamp(streams,1,max))}
async function requestWithRetry(request,bytes,maxRetries){let retries=0;while(true){try{return{point:await request(bytes),retries}}catch(e){if(e.name==='AbortError')throw e;if(retries>=maxRetries)throw e;retries++;await sleep(100*retries)}}}
async function runBurst(direction,estimate,quick,maxRetries,streams){const request=direction==='download'?window.downloadRequest:window.uploadRequest,targetSeconds=quick?.62:(performanceProfile==='mobile'?1.14:.96),minBytes=direction==='download'?850_000:420_000,maxTotal=quick?(direction==='download'?14_000_000:7_000_000):(performanceProfile==='mobile'?(direction==='download'?42_000_000:22_000_000):(direction==='download'?62_000_000:30_000_000)),totalTarget=clamp(estimate*1e6/8*targetSeconds,minBytes,maxTotal),perStream=Math.round(clamp(totalTarget/streams,direction==='download'?300_000:200_000,direction==='download'?18_000_000:9_000_000)),started=performance.now(),settled=await Promise.allSettled(Array.from({length:streams},()=>requestWithRetry(request,perStream,maxRetries))),elapsedMs=performance.now()-started;let bytes=0,retries=0,failures=0,successes=0;for(const item of settled){if(item.status==='fulfilled'){bytes+=Number(item.value.point.bytes)||perStream;retries+=item.value.retries;successes++}else{if(item.reason?.name==='AbortError')throw item.reason;failures++}}if(!successes)throw new Error(`${direction} burst gagal.`);return{mbps:bytes*8/(elapsedMs/1000)/1e6,bytes,seconds:elapsedMs/1000,streams,successes,retries,failures}}

if(await waitForCore()){
  const session={version:6,method:'performance-aware-saturation-http',performanceProfile,startedAt:0,endedAt:0,status:'idle',phases:{},totalBytes:0,totalRetries:0,totalFailures:0,calibrationBytes:0,edge:{start:null,end:null,changed:false},performance:{profile:performanceProfile,cores,memory:memory||null,frameStalls:0,worstFrameGapMs:0},integrity:{networkChanged:false,visibilityInterrupted:false,offlineDuringTest:false,connectionStart:null,connectionEnd:null,changeEvents:0,hiddenEvents:0}};
  window.wifiMeasurementSession=session;
  const engine=document.getElementById('engineState');let rafId=0,lastFrame=performance.now();
  const frameMonitor=now=>{if(session.status==='running'){const gap=now-lastFrame;if(gap>110){session.performance.frameStalls++;session.performance.worstFrameGapMs=Math.max(session.performance.worstFrameGapMs,gap)}}lastFrame=now;rafId=requestAnimationFrame(frameMonitor)};rafId=requestAnimationFrame(frameMonitor);
  const resetSession=()=>{session.version=6;session.method='performance-aware-saturation-http';session.performanceProfile=performanceProfile;session.startedAt=performance.now();session.endedAt=0;session.durationMs=0;session.status='running';session.phases={};session.totalBytes=0;session.calibrationBytes=0;session.totalRetries=0;session.totalFailures=0;session.performance={profile:performanceProfile,cores,memory:memory||null,frameStalls:0,worstFrameGapMs:0};session.edge={start:null,end:null,changed:false};session.integrity={networkChanged:false,visibilityInterrupted:false,offlineDuringTest:false,connectionStart:snapshotConnection(),connectionEnd:null,changeEvents:0,hiddenEvents:0};lastFrame=performance.now();readEdge().then(x=>{session.edge.start=x});window.dispatchEvent(new CustomEvent('wifi-measurement-reset',{detail:{version:6,performanceProfile}}))};
  const finishSession=status=>{session.endedAt=performance.now();session.status=status;session.durationMs=session.startedAt?session.endedAt-session.startedAt:0;session.integrity.connectionEnd=snapshotConnection();if(!sameConnection(session.integrity.connectionStart,session.integrity.connectionEnd))session.integrity.networkChanged=true;window.dispatchEvent(new CustomEvent('wifi-measurement-session',{detail:clone(session)}));readEdge().then(x=>{session.edge.end=x;session.edge.changed=Boolean(session.edge.start?.colo&&x?.colo&&session.edge.start.colo!==x.colo);if(session.edge.changed)session.integrity.networkChanged=true;window.dispatchEvent(new CustomEvent('wifi-measurement-audit',{detail:clone(session)}))})};
  if(engine)new MutationObserver(()=>{const s=engine.textContent.trim().toUpperCase();if(s==='RUNNING')resetSession();else if(s==='COMPLETE')finishSession('complete');else if(s==='CANCELLED')finishSession('cancelled');else if(s==='ERROR')finishSession('error')}).observe(engine,{childList:true,characterData:true,subtree:true});
  connection?.addEventListener?.('change',()=>{if(session.status==='running'){session.integrity.changeEvents++;session.integrity.networkChanged=true}});document.addEventListener('visibilitychange',()=>{if(session.status==='running'&&document.visibilityState==='hidden'){session.integrity.hiddenEvents++;session.integrity.visibilityInterrupted=true}});addEventListener('offline',()=>{if(session.status==='running')session.integrity.offlineDuringTest=true});

  window.runLatency=async function(samples=12,onSample){const target=Math.max(samples,samples>=10?16:samples),started=performance.now(),vals=[];let failures=0,retries=0;window.dispatchEvent(new CustomEvent('wifi-test-phase',{detail:{phase:'ping',status:'running',engineVersion:6}}));for(let i=0;i<target;i++){let value=NaN;for(let attempt=0;attempt<2;attempt++){try{value=await window.latencyProbe();break}catch(e){if(e.name==='AbortError')throw e;if(attempt===0){retries++;await sleep(70)}else failures++}}if(Number.isFinite(value))vals.push(value);onSample?.(i+1,target,value);phase('Mengukur ping',Number.isFinite(value)?`${value.toFixed(1)} ms · ${i+1}/${target}`:`Sampel ${i+1}/${target} gagal`,{phase:'ping',status:'sample',sample:i+1,targetSamples:target,value,retries,failures});if(i+1<target)await sleep(performanceProfile==='mobile'?70:55)}if(vals.length<Math.max(5,Math.ceil(target*.58)))throw new Error('Sampel latency tidak cukup.');const stable=vals.length>5?vals.slice(1):vals,diffs=[];for(let i=1;i<stable.length;i++)diffs.push(Math.abs(stable[i]-stable[i-1]));const ping=median(stable),jitter=mean(diffs),elapsedMs=performance.now()-started,stats=summarize(stable,target-1,elapsedMs,retries,failures,{jitter,p95:percentile(stable,.95),p99:percentile(stable,.99)});session.phases.ping={...stats,ping,jitter};session.totalRetries+=retries;session.totalFailures+=failures;phase('Ping selesai',`${ping.toFixed(1)} ms · jitter ${jitter.toFixed(1)} · P95 ${stats.p95.toFixed(1)} ms`,{phase:'ping',status:'result',value:ping,unit:'ms',stats});await sleep(target>=10?700:320);return{ping,jitter,samples:stable,failed:failures,retries,stats}};

  window.adaptiveBandwidth=async function(direction,onPoint,quick=false){const isDown=direction==='download',targetBursts=quick?3:(performanceProfile==='mobile'?5:6),maxBursts=quick?5:(performanceProfile==='mobile'?(isDown?8:8):(isDown?10:9)),minElapsed=quick?1800:(performanceProfile==='mobile'?(isDown?5200:4800):(isDown?4900:4500)),hardCap=quick?(isDown?38_000_000:20_000_000):(performanceProfile==='mobile'?(isDown?190_000_000:105_000_000):(isDown?260_000_000:145_000_000)),points=[];let total=0,estimate=isDown?20:8,retries=0,failures=0,maxStreams=1,autoExtended=0,earlyStopped=false,calibrationStages=0;const started=performance.now();window.dispatchEvent(new CustomEvent('wifi-test-phase',{detail:{phase:direction,status:'running',engineVersion:6,performanceProfile}}));if(!quick){try{const cal1=await runBurst(direction,estimate,false,1,1);estimate=Math.max(1,cal1.mbps);session.calibrationBytes+=cal1.bytes;total+=cal1.bytes;calibrationStages++;phase(isDown?'Kalibrasi download':'Kalibrasi upload',`${cal1.mbps.toFixed(1)} Mbps · warm-up 1`,{phase:direction,status:'calibration',value:cal1.mbps,bytes:cal1.bytes,streams:1,stage:1});if(cal1.mbps>30){await nextFrame();const s2=Math.min(2,streamLimits(direction,false)),cal2=await runBurst(direction,estimate,false,1,s2);estimate=Math.max(estimate,cal2.mbps*.96);session.calibrationBytes+=cal2.bytes;total+=cal2.bytes;calibrationStages++;phase(isDown?'Kalibrasi download':'Kalibrasi upload',`${cal2.mbps.toFixed(1)} Mbps · saturation probe`,{phase:direction,status:'calibration',value:cal2.mbps,bytes:cal2.bytes,streams:s2,stage:2})}await nextFrame()}catch(e){if(e.name==='AbortError')throw e}}
    for(let i=0;i<maxBursts;i++){const elapsed=performance.now()-started,values=points.map(x=>x.mbps),conv=convergence(values),plateau=plateauState(points),enough=points.length>=targetBursts&&elapsed>=minElapsed;if(enough&&conv.converged&&(plateau.plateau||points.length>=targetBursts+1)){earlyStopped=true;break}if(total>=hardCap&&points.length>=Math.min(4,targetBursts))break;if(points.length>=targetBursts&&!conv.converged)autoExtended++;const streams=adaptiveStreams(direction,estimate,quick,i,points);maxStreams=Math.max(maxStreams,streams);try{const p=await runBurst(direction,estimate,quick,quick?1:2,streams);points.push(p);total+=p.bytes;retries+=p.retries;failures+=p.failures;if(Number.isFinite(p.mbps))estimate=estimate*.32+p.mbps*.68;onPoint?.(p,points.length,targetBursts);const running=points.map(x=>x.mbps),r=rejectOutliers(running),liveMedian=median(r.values),c=convergence(r.values),sat=plateauState(points);phase(isDown?'Mengukur download':'Mengukur upload',`${p.mbps.toFixed(1)} Mbps · ${streams} stream · convergence ${c.score}% · ${humanMB(total)}`,{phase:direction,status:'sample',sample:points.length,targetSamples:targetBursts,value:p.mbps,runningMedian:liveMedian,bytes:total,streams,retries,failures,convergence:c.score,autoExtended,saturationGain:sat.gain,plateau:sat.plateau})}catch(e){if(e.name==='AbortError')throw e;failures++;phase(isDown?'Download retry':'Upload retry','Burst gagal; engine melanjutkan pengukuran.',{phase:direction,status:'retry',sample:points.length+1,targetSamples:targetBursts,retries,failures})}await nextFrame();if(points.length<targetBursts||autoExtended)await sleep(quick?70:(performanceProfile==='mobile'?125:95))}
    const usable=points.map(p=>p.mbps).filter(Number.isFinite);if(usable.length<2)throw new Error(`${direction} gagal mendapat sampel cukup.`);const elapsedMs=performance.now()-started,sat=plateauState(points),stats=summarize(usable,targetBursts,elapsedMs,retries,failures,{bytes:total,peak:Math.max(...usable),maxStreams,bursts:points.length,autoExtended,earlyStopped,warmupDiscarded:!quick,calibrationStages,saturationPlateau:sat.plateau,saturationGain:sat.gain,performanceProfile,method:'performance-aware-saturation-burst'}),chosen=stats.sustained;session.phases[direction]={...stats,value:chosen};session.totalBytes+=total;session.totalRetries+=retries;session.totalFailures+=failures;phase(isDown?'Download selesai':'Upload selesai',`${chosen.toFixed(1)} Mbps · convergence ${stats.convergence}% · range ${stats.ci90Low.toFixed(1)}–${stats.ci90High.toFixed(1)} Mbps`,{phase:direction,status:'result',value:chosen,unit:'Mbps',samples:points.length,bytes:total,stats});await sleep(quick?380:760);return{mbps:chosen,points,stats}};

  window.measureLoadedLatency=async function(direction,bandwidthMbps){const isDown=direction==='download',estimate=Math.max(1,bandwidthMbps||1),streams=Math.min(baseStreams(direction,estimate,false),performanceProfile==='mobile'?(isDown?3:2):streamLimits(direction,false)),targetTotal=clamp(estimate*1e6/8*2.3,isDown?2_000_000:800_000,isDown?55_000_000:27_000_000),perStream=Math.round(targetTotal/streams);let done=false;const started=performance.now(),load=Promise.allSettled(Array.from({length:streams},()=>requestWithRetry(isDown?window.downloadRequest:window.uploadRequest,perStream,1))).finally(()=>{done=true}),probes=[];await sleep(90);while(!done&&probes.length<14){try{probes.push(await window.latencyProbe(3500))}catch(e){if(e.name==='AbortError')throw e}if(!done)await sleep(performanceProfile==='mobile'?130:110)}await load;const value=probes.length?median(probes):NaN;session.phases[isDown?'loadedDownload':'loadedUpload']={value,samples:probes,p75:percentile(probes,.75),p95:percentile(probes,.95),streams,elapsedMs:performance.now()-started};return value};

  window.wifiCheckerEngineV6={version:6,realSampling:true,multiStream:true,warmupCalibration:true,twoStageCalibration:true,adaptiveStreamRamping:true,saturationPlateauDetection:true,performanceAwareConcurrency:true,uiFrameMonitoring:true,robustOutlierRejection:true,convergenceControl:true,confidenceRange:true,contentionHeuristics:true,edgeConsistency:true,integrityMonitoring:true,performanceProfile,session};
  window.dispatchEvent(new CustomEvent('wifi-engine-ready',{detail:{version:6,method:'performance-aware-saturation-http',performanceProfile}}));
}
