const q=s=>document.querySelector(s);
const qa=s=>[...document.querySelectorAll(s)];
const HISTORY_KEY='wifi-checker-pro-history-v2';
let lastSession=null,testStartedAt=0,livePhaseBytes={download:0,upload:0};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

async function waitForUI(){for(let i=0;i<160;i++){if(q('.meter-readouts')&&q('[data-workspace-panel="health"]')&&q('[data-workspace-panel="insights"]'))return true;await sleep(50)}return false}
function mb(bytes){return `${((bytes||0)/1e6).toFixed(bytes>=100e6?0:1)} MB`}
function sec(ms){return `${((ms||0)/1000).toFixed(1)} s`}
function tone(score){return score>=85?'green':score>=65?'yellow':score>=45?'orange':'red'}
function overallConfidence(s){const vals=[s?.phases?.ping?.confidence,s?.phases?.download?.confidence,s?.phases?.upload?.confidence].filter(Number.isFinite);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):NaN}
function overallStability(s){const vals=[s?.phases?.download?.stability,s?.phases?.upload?.stability].filter(Number.isFinite);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):NaN}
function parseDelta(){const m=(q('#bufferbloatDelta')?.textContent||'').match(/\+([\d.]+)/);return m?Number(m[1]):NaN}
function history(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function higherScore(v,bad,okay,good,excellent=good*2){
  if(!Number.isFinite(v))return 0;if(v<=bad)return clamp((v/bad)*30,0,30);if(v<=okay)return 30+((v-bad)/(okay-bad))*30;if(v<=good)return 60+((v-okay)/(good-okay))*25;return 85+clamp((v-good)/(excellent-good),0,1)*15
}
function lowerScore(v,excellent,good,okay,bad){
  if(!Number.isFinite(v))return 0;if(v<=excellent)return 100;if(v<=good)return 100-((v-excellent)/(good-excellent))*15;if(v<=okay)return 85-((v-good)/(okay-good))*25;if(v<=bad)return 60-((v-okay)/(bad-okay))*30;return Math.max(0,30-((v-bad)/bad)*30)
}
function profileState(score){return score>=78?['good','Siap']:score>=55?['warn','Cukup']:['bad','Kurang']}

function installTrafficDisclosure(){const row=qa('.permission-row').find(el=>/Traffic speed test/i.test(el.querySelector('b')?.textContent||''));const small=row?.querySelector('small');if(small)small.textContent='Traffic nyata ke Cloudflare edge. Full Test adaptif; pada koneksi sangat cepat penggunaan data dapat mendekati ~375 MB, biasanya jauh lebih rendah.'}
function installProof(){if(q('.measurement-proof'))return;const el=document.createElement('div');el.className='measurement-proof';el.innerHTML=`<div class="proof-cell" id="proofConfidence"><span>Confidence</span><b>—</b><small>kualitas sampel</small></div><div class="proof-cell" id="proofStability"><span>Stability</span><b>—</b><small>variasi throughput</small></div><div class="proof-cell" id="proofTraffic"><span>Traffic nyata</span><b>0 MB</b><small>download + upload</small></div><div class="proof-cell" id="proofDuration"><span>Durasi</span><b>0.0 s</b><small>waktu pengukuran</small></div>`;const anchor=q('.quality-legend')||q('.meter-readouts');anchor?.after(el)}
function installHealth(){
  const panel=q('[data-workspace-panel="health"]');if(!panel||q('#measurementQualityCard'))return;
  const card=document.createElement('article');card.id='measurementQualityCard';card.className='panel dock-card intel-summary-card';card.innerHTML=`<div class="intel-summary-head"><div><span>MEASUREMENT QUALITY</span><strong>Validasi hasil tes</strong></div><span id="measurementBadge" class="intel-badge">Belum diuji</span></div><div class="measure-section-title">Download</div><div class="measure-grid"><div class="measure-stat"><span>Median</span><b id="iqDownMedian">—</b><small>hasil utama</small></div><div class="measure-stat"><span>Peak</span><b id="iqDownPeak">—</b><small>puncak sampel</small></div><div class="measure-stat"><span>Stability</span><b id="iqDownStability">—</b><small>semakin tinggi lebih stabil</small></div><div class="measure-stat"><span>Samples</span><b id="iqDownSamples">—</b><small>sampel stabil</small></div></div><div class="measure-section-title">Upload & reliability</div><div class="measure-grid"><div class="measure-stat"><span>Upload median</span><b id="iqUpMedian">—</b><small>hasil utama</small></div><div class="measure-stat"><span>Upload stability</span><b id="iqUpStability">—</b><small>variasi throughput</small></div><div class="measure-stat"><span>Request success</span><b id="iqSuccess">—</b><small>bukan packet loss</small></div><div class="measure-stat"><span>Retry</span><b id="iqRetries">—</b><small>request yang diulang</small></div></div><p class="measure-note">Speed/stability: semakin tinggi semakin baik. Ping/jitter/loaded latency: semakin rendah semakin baik. Request success bukan packet loss.</p>`;panel.prepend(card)
}
function installUseCases(){
  const panel=q('[data-workspace-panel="insights"]');if(!panel||q('#useCaseCard'))return;
  const card=document.createElement('article');card.id='useCaseCard';card.className='panel dock-card intel-summary-card';card.innerHTML=`<div class="intel-summary-head"><div><span>CONNECTION PROFILE</span><strong>Cocok untuk apa?</strong></div><span id="profileBadge" class="intel-badge">Menunggu tes</span></div><div class="usecase-grid"><div class="usecase" data-use="gaming"><span class="usecase-icon"><i data-lucide="gamepad-2"></i></span><span class="usecase-copy"><b>Gaming</b><small>ping + jitter + loaded latency</small></span><span class="usecase-status">—</span></div><div class="usecase" data-use="call"><span class="usecase-icon"><i data-lucide="video"></i></span><span class="usecase-copy"><b>Video Call</b><small>upload + latency + stability</small></span><span class="usecase-status">—</span></div><div class="usecase" data-use="stream"><span class="usecase-icon"><i data-lucide="tv"></i></span><span class="usecase-copy"><b>4K Streaming</b><small>download + stability</small></span><span class="usecase-status">—</span></div><div class="usecase" data-use="cloud"><span class="usecase-icon"><i data-lucide="cloud-upload"></i></span><span class="usecase-copy"><b>Cloud / Upload</b><small>upload + stability</small></span><span class="usecase-status">—</span></div></div><div class="trend-row"><div><span>Download vs lalu</span><b id="trendDown">—</b></div><div><span>Upload vs lalu</span><b id="trendUp">—</b></div><div><span>Ping vs lalu</span><b id="trendPing">—</b></div></div>`;panel.prepend(card);try{window.lucide?.createIcons({attrs:{'stroke-width':1.8}})}catch{}
}
function setProof(id,value,sub,score){const el=q(id);if(!el)return;el.querySelector('b').textContent=value;if(sub)el.querySelector('small').textContent=sub;el.dataset.tone=Number.isFinite(score)?tone(score):''}
function updateProof(s,live=false,extraBytes=0){const conf=overallConfidence(s),stable=overallStability(s);setProof('#proofConfidence',Number.isFinite(conf)?`${conf}%`:'Mengukur…',Number.isFinite(conf)?`${conf>=85?'tinggi':conf>=65?'baik':conf>=45?'sedang':'rendah'}`:'mengumpulkan sampel',conf);setProof('#proofStability',Number.isFinite(stable)?`${stable}%`:'—','semakin tinggi lebih baik',stable);setProof('#proofTraffic',mb((s?.totalBytes||0)+Math.max(0,extraBytes)),'download + upload');const dur=s?.durationMs||(testStartedAt?performance.now()-testStartedAt:0);setProof('#proofDuration',sec(dur),live?'sedang berjalan':'waktu pengukuran');q('.measurement-proof')?.classList.toggle('measurement-live',live)}
function setUse(name,state,label,score){const el=q(`[data-use="${name}"]`);if(!el)return;el.classList.remove('good','warn','bad');el.classList.add(state);const status=el.querySelector('.usecase-status');status.textContent=`${label} · ${Math.round(score)}`}
function evaluateUseCases(s){
  const ping=s?.phases?.ping?.ping??Number(q('#pingValue')?.textContent),jitter=s?.phases?.ping?.jitter??Number(q('#jitterValue')?.textContent),down=s?.phases?.download?.value??Number(q('#downloadValue')?.textContent),up=s?.phases?.upload?.value??Number(q('#uploadValue')?.textContent),ds=s?.phases?.download?.stability??0,us=s?.phases?.upload?.stability??0,delta=parseDelta(),conf=overallConfidence(s);
  const pingScore=lowerScore(ping,20,45,80,140),jitterScore=lowerScore(jitter,4,10,20,40),loadedScore=Number.isFinite(delta)?lowerScore(delta,10,25,60,120):70;
  const downScore=higherScore(down,5,15,35,100),upScore=higherScore(up,2,5,15,50),downStable=clamp(ds,0,100),upStable=clamp(us,0,100),confidence=Number.isFinite(conf)?conf:65;
  const gaming=.46*pingScore+.28*jitterScore+.20*loadedScore+.06*Math.min(downScore,upScore);
  const call=.30*upScore+.24*pingScore+.18*jitterScore+.18*upStable+.10*confidence;
  const stream=.64*downScore+.22*downStable+.08*loadedScore+.06*confidence;
  const cloud=.68*upScore+.22*upStable+.05*pingScore+.05*confidence;
  const profiles={gaming,call,stream,cloud};Object.entries(profiles).forEach(([name,score])=>{const [state,label]=profileState(score);setUse(name,state,label,score)});
  const overall=Math.round((gaming+call+stream+cloud)/4),badge=q('#profileBadge');if(badge){const [state,label]=profileState(overall);badge.className='intel-badge '+state;badge.textContent=`${label} · ${overall}/100`}
}
function trendText(current,previous,lowerBetter=false){if(!Number.isFinite(current)||!Number.isFinite(previous)||previous===0)return{text:'—',cls:'trend-neutral'};const pct=((current-previous)/previous)*100;const better=lowerBetter?pct<0:pct>0;const near=Math.abs(pct)<3;return{text:`${pct>=0?'+':''}${pct.toFixed(0)}%`,cls:near?'trend-neutral':better?'trend-up':'trend-down'}}
function updateTrends(){const h=history();if(h.length<2)return;const cur=h[0],prev=h[1];[['#trendDown',cur.download,prev.download,false],['#trendUp',cur.upload,prev.upload,false],['#trendPing',cur.ping,prev.ping,true]].forEach(([sel,a,b,lower])=>{const el=q(sel),t=trendText(Number(a),Number(b),lower);if(el){el.textContent=t.text;el.className=t.cls}})}
function updateHealth(s){const d=s?.phases?.download,u=s?.phases?.upload,p=s?.phases?.ping,conf=overallConfidence(s),badge=q('#measurementBadge');if(badge){badge.className='intel-badge '+(conf>=85?'good':conf>=60?'warn':'bad');badge.textContent=Number.isFinite(conf)?`Confidence ${conf}%`:'Belum diuji'}q('#iqDownMedian').textContent=Number.isFinite(d?.median)?`${d.median.toFixed(1)} Mbps`:'—';q('#iqDownPeak').textContent=Number.isFinite(d?.peak)?`${d.peak.toFixed(1)} Mbps`:'—';q('#iqDownStability').textContent=Number.isFinite(d?.stability)?`${d.stability}%`:'—';q('#iqDownSamples').textContent=Number.isFinite(d?.count)?`${d.count} stabil`:'—';q('#iqUpMedian').textContent=Number.isFinite(u?.median)?`${u.median.toFixed(1)} Mbps`:'—';q('#iqUpStability').textContent=Number.isFinite(u?.stability)?`${u.stability}%`:'—';const counts=[d,u,p].filter(Boolean),success=counts.length?Math.round(counts.reduce((a,x)=>a+(x.successRate||100),0)/counts.length):NaN;q('#iqSuccess').textContent=Number.isFinite(success)?`${success}%`:'—';q('#iqRetries').textContent=String(s?.totalRetries??'—')}
function snapshotSession(){const s=window.wifiMeasurementSession;if(!s)return null;try{return JSON.parse(JSON.stringify(s))}catch{return s}}
function enrichExport(){const original=window.safeExport;if(typeof original!=='function'||original.__intelWrapped)return;const wrapped=function(){const data=original();if(data){const s=snapshotSession();data.measurementQuality=s?{engineVersion:s.version,durationMs:s.durationMs,totalBytes:s.totalBytes,totalRetries:s.totalRetries,totalFailures:s.totalFailures,phases:s.phases}:null}return data};wrapped.__intelWrapped=true;window.safeExport=wrapped}

if(await waitForUI()){
  installTrafficDisclosure();installProof();installHealth();installUseCases();enrichExport();
  window.addEventListener('wifi-measurement-reset',()=>{testStartedAt=performance.now();livePhaseBytes={download:0,upload:0};lastSession=window.wifiMeasurementSession;updateProof(lastSession,true);const badge=q('#measurementBadge');if(badge){badge.className='intel-badge';badge.textContent='Mengukur…'}});
  window.addEventListener('wifi-test-phase',e=>{const d=e.detail||{},s=window.wifiMeasurementSession;if((d.phase==='download'||d.phase==='upload')&&d.status==='sample'&&Number.isFinite(Number(d.bytes)))livePhaseBytes[d.phase]=Number(d.bytes);if((d.phase==='download'||d.phase==='upload')&&d.status==='result')livePhaseBytes[d.phase]=0;const extra=(d.phase==='download'||d.phase==='upload')?livePhaseBytes[d.phase]:0;updateProof(s,true,extra)});
  window.addEventListener('wifi-measurement-session',e=>{lastSession=e.detail||snapshotSession();livePhaseBytes={download:0,upload:0};updateProof(lastSession,false);updateHealth(lastSession);evaluateUseCases(lastSession);setTimeout(updateTrends,120);enrichExport()});
  const engine=q('#engineState');if(engine)new MutationObserver(()=>{if(engine.textContent.trim().toUpperCase()==='COMPLETE'&&lastSession){updateHealth(lastSession);evaluateUseCases(lastSession);setTimeout(updateTrends,160)}}).observe(engine,{childList:true,characterData:true,subtree:true});
}
