const q=s=>document.querySelector(s);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;

function waitForGauge(){return new Promise(resolve=>{let tries=0;const tick=()=>{const gauge=q('.clean-gauge'),oldNeedle=q('#gaugeNeedle'),oldProgress=q('#gaugeProgress'),oldCenter=q('.clean-gauge .gauge-center'),oldLabels=q('.clean-gauge .gauge-labels');if(gauge&&oldNeedle&&oldProgress&&oldCenter&&oldLabels)return resolve({gauge,oldNeedle,oldProgress,oldCenter,oldLabels});if(++tries<160)setTimeout(tick,50)};tick()})}
function prettyScale(v){const tiers=[10,25,50,75,100,150,200,300,500,750,1000,1500,2000,2500,5000,10000],wanted=Math.max(10,v);return tiers.find(x=>x>=wanted)||Math.ceil(wanted/5000)*5000}
let unitMode='auto';
function displayValue(mbps){const mode=unitMode;if(mode==='gbps'||(mode==='auto'&&mbps>=1000))return{v:mbps/1000,u:'Gbps',d:2};if(mode==='kbps'||(mode==='auto'&&mbps<1))return{v:mbps*1000,u:'Kbps',d:mbps<.1?1:0};if(mode==='MBps')return{v:mbps/8,u:'MB/s',d:2};return{v:mbps,u:'Mbps',d:mbps>=100?0:1}}
function sessionValue(kind){const p=window.wifiMeasurementSession?.phases?.[kind],v=Number(p?.value ?? (kind==='ping'?p?.ping:NaN));return Number.isFinite(v)?v:NaN}

waitForGauge().then(({gauge,oldNeedle,oldProgress,oldCenter,oldLabels})=>{
  const unitSelect=q('#speedUnitSelect');unitMode=unitSelect?.value||'auto';
  oldNeedle.style.opacity='0';oldProgress.style.opacity='0';oldCenter.style.opacity='0';oldLabels.style.opacity='0';
  const progress=oldProgress.cloneNode(true);progress.id='flowGaugeProgress';progress.classList.add('flow-gauge-progress');progress.style.opacity='1';oldProgress.after(progress);
  const needle=oldNeedle.cloneNode(true);needle.id='flowGaugeNeedle';needle.classList.add('flow-gauge-needle');needle.style.opacity='1';oldNeedle.after(needle);
  const center=oldCenter.cloneNode(true);center.classList.add('flow-gauge-center');center.style.opacity='1';center.querySelector('#gaugeLabel').id='flowGaugeLabel';center.querySelector('#gaugeValue').id='flowGaugeValue';center.querySelector('#gaugeUnit').id='flowGaugeUnit';oldCenter.after(center);
  const labels=oldLabels.cloneNode(true);labels.classList.add('flow-gauge-labels');labels.style.opacity='1';labels.querySelector('#gaugeMid').id='flowGaugeMid';labels.querySelector('#gaugeMax').id='flowGaugeMax';oldLabels.after(labels);

  const card=q('.meter-card');let steps=q('.phase-steps');if(!steps){steps=document.createElement('div');steps.className='phase-steps';steps.innerHTML='<span data-phase="ping"><i></i>Ping</span><span data-phase="download"><i></i>Download</span><span data-phase="upload"><i></i>Upload</span>';card?.querySelector('.instrument-top')?.after(steps)}
  let transition=q('.phase-transition');if(!transition){transition=document.createElement('div');transition.className='phase-transition show';transition.innerHTML='<span id="phaseTransitionLabel">SIAP</span><strong id="phaseTransitionValue">Tekan GO untuk mulai</strong><small id="phaseTransitionMeta">Pengukuran menggunakan traffic nyata ke Cloudflare edge.</small>';const readouts=q('.meter-readouts');if(readouts)readouts.before(transition);else card?.append(transition)}

  const valueEl=q('#flowGaugeValue'),unitEl=q('#flowGaugeUnit'),labelEl=q('#flowGaugeLabel'),scaleMid=q('#flowGaugeMid'),scaleMax=q('#flowGaugeMax');
  const readoutDown=q('#meterDown'),readoutUp=q('#meterUp'),readoutPing=q('#meterPing'),phaseLabel=q('#phaseTransitionLabel'),phaseValue=q('#phaseTransitionValue'),phaseMeta=q('#phaseTransitionMeta');
  const stepEls={ping:steps?.querySelector('[data-phase="ping"]'),download:steps?.querySelector('[data-phase="download"]'),upload:steps?.querySelector('[data-phase="upload"]')};
  const state={angle:135,raw:0,targetRaw:0,displayMax:100,targetMax:100,kind:'idle',label:'SPEED TEST',last:performance.now(),liveEstimator:NaN,phaseSamples:[],scaleLocked:false,finalTarget:false,lastValue:'',lastUnit:'',lastLabel:'',lastDash:'',lastTransform:'',lastScale:-1,lastCenterPaintAt:0,lastReadoutAt:0,lastSampleUiAt:0};

  function setText(el,text){if(el&&el.textContent!==text)el.textContent=text}
  function paintReadout(kind,raw,force=false){const now=performance.now();if(!force&&now-state.lastReadoutAt<70)return;state.lastReadoutAt=now;const c=displayValue(raw),el=kind==='download'?readoutDown:readoutUp;if(!el)return;const value=c.v.toFixed(c.d),small=el.querySelector('small');if(el.firstChild?.nodeType===3){const wanted=`${value} `;if(el.firstChild.nodeValue!==wanted)el.firstChild.nodeValue=wanted}else{el.textContent=`${value} `;const s=document.createElement('small');s.textContent=c.u;el.append(s);return}if(small)setText(small,c.u)}
  function setScaleTarget(next,force=false){next=Math.max(10,Number(next)||10);if(!force&&next===state.targetMax)return;state.targetMax=next;const half=displayValue(next/2),full=displayValue(next);setText(scaleMid,String(Number(half.v.toFixed(half.d))));setText(scaleMax,`${Number(full.v.toFixed(full.d))} ${full.u}`);state.lastScale=next}
  function beginPhase(kind,label,seed=0){if(kind===state.kind)return;state.kind=kind;state.label=label||kind.toUpperCase();state.phaseSamples=[];state.liveEstimator=NaN;state.scaleLocked=false;state.finalTarget=false;state.targetRaw=Math.max(0,seed);const baseline=kind==='upload'?25:50;setScaleTarget(prettyScale(Math.max(baseline,seed*1.6)),true);gauge.dataset.metric=kind}
  function ensureScale(value,margin=1.5){if(!Number.isFinite(value)||value<=0)return;if(!state.scaleLocked){setScaleTarget(prettyScale(Math.max(value*margin,state.kind==='upload'?25:50)));state.scaleLocked=true;return}if(value>state.targetMax*.92)setScaleTarget(prettyScale(value*1.38))}
  function liveCandidate(d){const raw=Number(d.value),medianValue=Number(d.runningMedian),candidate=Number.isFinite(medianValue)&&medianValue>0?medianValue:raw;if(!Number.isFinite(candidate))return NaN;state.phaseSamples.push(raw);if(state.phaseSamples.length>12)state.phaseSamples.shift();if(!Number.isFinite(state.liveEstimator))state.liveEstimator=candidate;else{const delta=Math.abs(candidate-state.liveEstimator),relative=delta/Math.max(1,state.liveEstimator),alpha=relative>.45?.22:relative>.20?.30:.38;state.liveEstimator+=((candidate-state.liveEstimator)*alpha)}return state.liveEstimator}
  function setLiveTarget(value,kind,label){if(!Number.isFinite(value))return;if(kind!==state.kind)beginPhase(kind,label,value);ensureScale(value);state.finalTarget=false;state.targetRaw=Math.max(0,value);state.label=label||kind.toUpperCase();gauge.dataset.metric=kind}
  function setFinalTarget(value,kind,label){if(!Number.isFinite(value))return;if(kind!==state.kind)beginPhase(kind,label,value);ensureScale(value,1.38);state.finalTarget=true;state.liveEstimator=value;state.targetRaw=Math.max(0,value);state.label=label||`${kind.toUpperCase()} HASIL`;gauge.dataset.metric=kind}
  function approach(current,target,dt,rate){const diff=target-current;if(Math.abs(diff)<.0001)return target;const response=1-Math.exp(-dt/(state.finalTarget?.30:.62)),step=diff*response,maxStep=Math.max(.025,rate*dt);return current+clamp(step,-maxStep,maxStep)}
  function frame(now){
    const dt=Math.min(.05,Math.max(.001,(now-state.last)/1000));state.last=now;
    const basis=Math.max(8,state.raw,state.targetRaw),rate=reduced?1e9:Math.max(4,basis*(state.finalTarget?1.35:.46));state.raw=reduced?state.targetRaw:approach(state.raw,state.targetRaw,dt,rate);
    const maxResponse=reduced?1:1-Math.exp(-dt/.58);state.displayMax+=((state.targetMax-state.displayMax)*maxResponse);state.displayMax=Math.max(10,state.displayMax);
    const desiredAngle=135+clamp(state.raw/state.displayMax,0,1)*270,angleResponse=reduced?1:1-Math.exp(-dt/.13);state.angle+=(desiredAngle-state.angle)*angleResponse;
    if(state.finalTarget&&Math.abs(state.targetRaw-state.raw)<.025)state.raw=state.targetRaw;
    const transform=`rotate(${state.angle.toFixed(3)} 160 160)`;if(transform!==state.lastTransform){needle.setAttribute('transform',transform);state.lastTransform=transform}
    const dash=String((100-clamp((state.angle-135)/270,0,1)*100).toFixed(3));if(dash!==state.lastDash){progress.style.strokeDashoffset=dash;state.lastDash=dash}
    if(now-state.lastCenterPaintAt>=33||state.finalTarget&&state.raw===state.targetRaw){state.lastCenterPaintAt=now;const shown=displayValue(Math.max(0,state.raw)),value=shown.v.toFixed(shown.d);if(value!==state.lastValue){setText(valueEl,value);state.lastValue=value}if(shown.u!==state.lastUnit){setText(unitEl,shown.u);state.lastUnit=shown.u}if(state.label!==state.lastLabel){setText(labelEl,state.label);state.lastLabel=state.label}if(state.kind==='download'||state.kind==='upload')paintReadout(state.kind,state.raw,state.finalTarget&&state.raw===state.targetRaw)}
    requestAnimationFrame(frame)
  }
  requestAnimationFrame(frame);

  function setStep(phase,status){const el=stepEls[phase];if(!el)return;if(status==='running'){el.classList.add('active');el.classList.remove('done')}if(status==='result'){el.classList.remove('active');el.classList.add('done')}}
  function showTransition(label,value,meta,tone='neutral'){if(!transition)return;transition.classList.remove('tone-green','tone-yellow','tone-orange','tone-red');if(tone!=='neutral')transition.classList.add(`tone-${tone}`);setText(phaseLabel,label);setText(phaseValue,value);setText(phaseMeta,meta||'');transition.classList.add('show')}
  function updateSampleTransition(d,visual){const now=performance.now();if(now-state.lastSampleUiAt<220)return;state.lastSampleUiAt=now;const conv=Number(d.convergence),ext=Number(d.autoExtended)||0;setText(phaseLabel,d.phase.toUpperCase());setText(phaseValue,`${visual.toFixed(1)} Mbps`);setText(phaseMeta,`live stabil · ${Number(d.streams)||1} stream · convergence ${Number.isFinite(conv)?Math.round(conv)+'%':'—'}${ext?` · +${ext} burst`:''}`)}
  function latencyTone(v){return v<=25?'green':v<=50?'yellow':v<=100?'orange':'red'}
  function speedTone(v,kind){return kind==='upload'?(v>=20?'green':v>=10?'yellow':v>=3?'orange':'red'):(v>=50?'green':v>=25?'yellow':v>=10?'orange':'red')}

  window.addEventListener('wifi-test-phase',e=>{
    const d=e.detail||{};if(!d.phase)return;setStep(d.phase,d.status);
    if(d.status==='running'){const names={ping:'PING',download:'DOWNLOAD',upload:'UPLOAD'};if(d.phase==='download'||d.phase==='upload')beginPhase(d.phase,names[d.phase],0);showTransition(names[d.phase]||'MENGUKUR','Sedang mengukur…',d.phase==='ping'?'Latency: semakin rendah semakin baik.':'Engine v6 mengukur burst nyata; meter menampilkan estimator live yang dihaluskan.')}
    if(d.status==='calibration'&&Number.isFinite(Number(d.value))){const v=Number(d.value);if(d.phase!==state.kind)beginPhase(d.phase,'KALIBRASI',v);ensureScale(v,1.65);state.liveEstimator=Number.isFinite(state.liveEstimator)?state.liveEstimator+(v-state.liveEstimator)*.34:v;state.targetRaw=state.liveEstimator;state.label='KALIBRASI';showTransition('KALIBRASI',`${v.toFixed(1)} Mbps`,'Warm-up nyata untuk menentukan saturasi. Sampel ini tidak menjadi hasil final.')}
    if(d.status==='sample'&&Number.isFinite(Number(d.value))&&(d.phase==='download'||d.phase==='upload')){const visual=liveCandidate(d);if(Number.isFinite(visual)){setLiveTarget(visual,d.phase,d.phase.toUpperCase());updateSampleTransition(d,visual)}}
    if(d.status==='result'){
      if(d.phase==='ping'){const ping=Number(d.value);if(readoutPing){const small=readoutPing.querySelector('small');if(readoutPing.firstChild?.nodeType===3)readoutPing.firstChild.nodeValue=`${ping.toFixed(1)} `;if(small)setText(small,'ms')}const p95=Number(d.stats?.p95);showTransition('PING SELESAI',`${ping.toFixed(1)} ms`,Number.isFinite(p95)?`P95 ${p95.toFixed(1)} ms · semakin rendah semakin baik.`:'Semakin rendah semakin baik.',latencyTone(ping))}
      else{const speed=Number(d.value),stats=d.stats||{},streams=Number(stats.maxStreams);setFinalTarget(speed,d.phase,`${d.phase.toUpperCase()} HASIL`);const range=Number.isFinite(stats.ci90Low)&&Number.isFinite(stats.ci90High)?`range ${stats.ci90Low.toFixed(1)}–${stats.ci90High.toFixed(1)} · `:'';showTransition(`${d.phase.toUpperCase()} SELESAI`,`${speed.toFixed(1)} Mbps`,`${Number.isFinite(streams)?`${streams} stream · `:''}${range}convergence ${Math.round(stats.convergence||0)}%`,speedTone(speed,d.phase))}
    }
  },{passive:true});

  window.addEventListener('wifi-measurement-session',e=>{const session=e.detail||window.wifiMeasurementSession;if(session?.status!=='complete')return;const down=Number(session?.phases?.download?.value),up=Number(session?.phases?.upload?.value),ping=Number(session?.phases?.ping?.ping);if(Number.isFinite(ping)&&readoutPing){const small=readoutPing.querySelector('small');if(readoutPing.firstChild?.nodeType===3)readoutPing.firstChild.nodeValue=`${ping.toFixed(1)} `;if(small)setText(small,'ms')}if(Number.isFinite(up)){const c=displayValue(up),small=readoutUp?.querySelector('small');if(readoutUp?.firstChild?.nodeType===3)readoutUp.firstChild.nodeValue=`${c.v.toFixed(c.d)} `;if(small)setText(small,c.u)}if(Number.isFinite(down))setFinalTarget(down,'download','HASIL DOWNLOAD')});

  const stage=q('#testStage');if(stage)new MutationObserver(()=>{const text=stage.textContent.toLowerCase();if(text.includes('loaded latency'))showTransition('ANALISIS JARINGAN','Mengukur loaded latency…','Latency tambahan saat koneksi sibuk: semakin rendah semakin baik.');else if(text.includes('dns'))showTransition('DNS CHECK','Menguji resolver…','Tahap akhir diagnostik sebelum hasil dikunci.')}).observe(stage,{childList:true,characterData:true,subtree:true});
  const engine=q('#engineState');if(engine)new MutationObserver(()=>{const s=engine.textContent.trim().toUpperCase();if(s==='RUNNING'){Object.values(stepEls).filter(Boolean).forEach(el=>el.classList.remove('done','active'));state.kind='idle';state.phaseSamples=[];state.liveEstimator=NaN;state.scaleLocked=false;state.finalTarget=false;state.targetRaw=0;state.targetMax=100;state.label='PING';setScaleTarget(100,true)}if(s==='COMPLETE'){Object.values(stepEls).filter(Boolean).forEach(el=>{el.classList.remove('active');el.classList.add('done')});const exact=sessionValue('download');if(Number.isFinite(exact))setFinalTarget(exact,'download','HASIL DOWNLOAD');showTransition('TES SELESAI','Semua pengukuran selesai','Hasil final memakai sustained result Engine v6; smoothing hanya untuk tampilan live.','green')}}).observe(engine,{childList:true,characterData:true,subtree:true});
  unitSelect?.addEventListener('change',()=>{unitMode=unitSelect.value||'auto';state.lastValue='';state.lastUnit='';state.lastScale=-1;setScaleTarget(state.targetMax,true)});
  setScaleTarget(100,true);
  window.wifiSmoothMeter={version:3,continuousEstimator:true,usesRunningMedian:true,scaleInterpolation:true,finalResultUnsmoothened:true};
}).catch(()=>{});
